spring: 
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev     #开发环境
  application:
    name: microsrvicecloud-config-wjh-dev
---
spring:
  profile: test     #测试环境
  application:
    name: microsrvicecloud-config-wjh-test
#请保存为UTF-8格式
 

